export const QueryKeys = {
  SOCKET: "socket",
  ME: "me",
  DASHBOARD: "dashboard",
  CATEGORIES: "categories",
  BRANDS: "brands",
  SAVED_PRODUCTS: "saved_products",
  PURCHASED_PRODUCTS: "purchased_products",
  TRANSACTIONS: "saved_products",
  PAYOUT_HISTORY: "payout_history",
  NOTIFICATION_LIST: "notification_list",
  PAYMENT_CARD_LIST: "payment_card_list",
  PRODUCT_DETAILS: "product_details",
  SEARCH_PRODUCT: "search_product",
  DEALS: "deals",
  PRODUCTS: "products",
  SUB_CATEGORIES: "sub_categories",
  ALL_CHAT_LIST: "all_chat_list",
  CHAT_MESSAGE_LIST: "chat_message_list",
};
